insert into localities (id, locality, postal_code) values (1, 'Bruxelles', '1000');
insert into localities (id, locality, postal_code) values (2, 'Farīmān', '1019');
insert into localities (id, locality, postal_code) values (3, 'Carrizal', '1040');
insert into localities (id, locality, postal_code) values (4, 'Fresno', '1070');
insert into localities (id, locality, postal_code) values (5, 'Changuillo', '1090');
insert into localities (id, locality, postal_code) values (6, 'Żabno', '1080');
insert into localities (id, locality, postal_code) values (7, 'San Vicente', '2000');
insert into localities (id, locality, postal_code) values (8, 'Nizhnekamsk', '3000');
insert into localities (id, locality, postal_code) values (9, 'Las Vegas', '4000');
insert into localities (id, locality, postal_code) values (10, 'Soledad', '6000');
insert into localities (id, locality, postal_code) values (11, 'Athi River', '4800');
insert into localities (id, locality, postal_code) values (12, 'Bor', '5000');
insert into localities (id, locality, postal_code) values (13, 'Alibunan', '5042');
insert into localities (id, locality, postal_code) values (14, 'Tiannan', '7000');
insert into localities (id, locality, postal_code) values (15, 'Benešov nad Ploučnicí', '7419');
insert into localities (id, locality, postal_code) values (16, 'Nsukka', '8419');
insert into localities (id, locality, postal_code) values (17, 'Vũ Quang', '6005');
insert into localities (id, locality, postal_code) values (18, 'Bangan-Oda', '2408');
insert into localities (id, locality, postal_code) values (19, 'Opechenskiy Posad', '8419');
insert into localities (id, locality, postal_code) values (20, 'Río de Oro', '9419');

insert into locations (id, slug, designation, address, locality_id, website, phone) values (1, 'theatre-royal-parc', 'Théâtre Royal du Parc', 'Rue de la Loi 3', 1, 'www.theatreduparc.be', '+3224100608');
insert into locations (id, slug, designation, address, locality_id, website, phone) values (2, 'la-samaritaine', 'La Samaritaine', 'Rue de la samaritaine 24', 17, 'www.lasamaritaine.be', '+3224850608');
insert into locations (id, slug, designation, address, locality_id, website, phone) values (3, 'belfius-art-collection', 'Belfius Art Collection', '50 rue de l''écuyer', 9, null, null);